# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=2000)),
                ('case_ref_no', models.CharField(default=None, max_length=200)),
                ('mentioned_in', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('doj', models.DateField()),
            ],
        ),
    ]
