# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='mentions',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='mentioned_in',
            field=models.IntegerField(default=0, help_text='No of times the case is mentioned in other cases'),
        ),
    ]
