# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171110_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='body',
            field=models.TextField(help_text='About the Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='mentions',
            field=models.CharField(default='', help_text='String Seperated ids of cases mentioned in this case', max_length=200),
        ),
    ]
