# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171110_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='mentions',
        ),
        migrations.AddField(
            model_name='case',
            name='mentions',
            field=models.ManyToManyField(blank=True, related_name='_case_mentions_+', to='home.Case'),
        ),
    ]
